version: "3.8"

services:
  node:
    build:
      dockerfile: Dockerfile
      context: .
    user: $UID:$GID
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9229:9229"
      - "9230:9230"
      - "33213:33213"
    environment:
      - NODE_ENV=development
      - INTERNAL_STATUS_PORT=33213
    volumes:
      - ./:/app
    command: node --inspect node_modules/gatsby/dist/bin/gatsby.js develop -H 0.0.0.0