version: "3.8"

services:
  node:
    build:
      dockerfile: Dockerfile
      context: .
    user: $UID:$GID
    ports:
      - "8000:8000"
      - "9229:9229"
    environment:
      - AWS_ACCESS_KEY_ID=hackathon
      - AWS_SECRET_ACCESS_KEY=hackathon_secret
    volumes:
      - ./:/app
    command: ["npm", "run", "develop"]
  s3:
    image: minio/minio
    user: $UID:$GID
    hostname: hackathon.s3-website.eu-central-1.amazonaws.com
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage/minio:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: secret123
    command: server --console-address "0.0.0.0:9001" --address "0.0.0.0:9000" /data